import { NextResponse } from 'next/server';

// Proof generation is now handled by Mysten Enoki on the client.
// This endpoint is no longer used.
export function POST() {
    return NextResponse.json(
        { error: 'This endpoint is deprecated. zkLogin proof is generated by Enoki.' },
        { status: 410 },
    );
}
